version: '3.7'

services:
  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dnc-hotel
      - POSTGRES_PASSWORD=dnc-hotel
      - POSTGRES_DB=db-v1
    volumes:
      - dnc-hotel-pg-db:/postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - dnc-hotel-redis-db:/redis/data

volumes:
  dnc-hotel-pg-db:
  dnc-hotel-redis-db:
