-- CreateTable
CREATE TABLE "hotels" (
    "id" SERIAL NOT NULL,
    "HOTEL_NAME" TEXT NOT NULL,
    "HOTEL_DESCRIPTION" TEXT NOT NULL,
    "HOTEL_ADDRESS" TEXT NOT NULL,
    "HOTEL_IMAGE" TEXT NOT NULL,
    "HOTEL_PRICE" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "hotels_pkey" PRIMARY KEY ("id")
);
